Added many git utilities and tidied up code

diff --git a/programs/get b/programs/get
--- a/programs/get
+++ b/programs/get
@@ -1,30 +1,30 @@
 #!/bin/bash
 set -e
 DB=$1
-ROW=$2
-COLUMN=$3
-
-if [[ $1 -eq 0 ]]; then
+FIELD="$2"
+ITEM="$3"
+# We want to ls the database is metadata isn't specified, but if it is, cat the file
+if [[ -z "$1" ]]; then
   echo "No input given" > "$TMP_ERROR_REASON"
   exit 1
 fi
 
-[[ -d /var/db/dino/"$DB" ]] || {
+if ! [[ -d /var/db/dino/"$DB" ]]; then
   echo "Nonexistent database" > "$TMP_ERROR_REASON"
   exit 1
-}
+fi
 
-[[ -d /var/db/dino/"$DB"/"$ROW" ]] || {
-  echo "Nonexistent row" > "$TMP_ERROR_REASON"
+
+if [[ -z "$FIELD" ]]; then
+  ls -1aA --ignore='.git' /var/db/dino/"$DB"
+  exit
+fi
+if [[ -z "$ITEM" ]]; then
+  ls -1aA --ignore='.git' /var/db/dino/"$DB"/"$FIELD"
+  exit
+fi
+cat /var/db/dino/"$DB"/"$FIELD"/"$ITEM" || {
+  echo "Nonexistent item" > "$TMP_ERROR_REASON"
   exit 1
 }
-
-[[ -f /var/db/dino/"$DB"/"$ROW"/"$COLUMN" ]] || {
-  echo "Nonexistent column" > "$TMP_ERROR_REASON"
-  exit 1
-}
-
-cat /var/db/dino/"$DB"/"$ROW"/"$COLUMN" || {
-  echo "Failed to read from database (DB row and column exist)" > "$TMP_ERROR_REASON"
-  exit 1
-}
+exit
